//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insights.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnuncioHistorico
    {
        public int codAnuncioHistorico { get; set; }
        public Nullable<int> codAnuncio { get; set; }
        public Nullable<int> codLocal { get; set; }
        public Nullable<System.DateTime> dataInicial { get; set; }
        public Nullable<System.DateTime> dataFinal { get; set; }
    
        public virtual Local Local { get; set; }
    }
}
