//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insights.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anuncio()
        {
            this.AnuncioHistoricos = new HashSet<AnuncioHistorico>();
        }
    
        public int codAnuncio { get; set; }
        public int codUsuario { get; set; }
        public string titulo { get; set; }
        public byte[] imagem { get; set; }
        public string texto { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public string site { get; set; }
        public string endereco { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<int> codPlano { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnuncioHistorico> AnuncioHistoricos { get; set; }
        public virtual Plano Plano { get; set; }
    }
}
