//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insights.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local
    {
        public int codLocal { get; set; }
        public Nullable<int> codLocalTipo { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> longitude { get; set; }
    
        public virtual LocalTipo LocalTipo { get; set; }
    }
}
