//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Insights.Infraestrutura.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plano
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plano()
        {
            this.LocaisTipos = new HashSet<LocalTipo>();
        }
    
        public int codPlano { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LocalTipo> LocaisTipos { get; set; }
    }
}
